### ISSUE TITLE
where to geit the file zht2zhs.ini

### ISSUE THREAD

**Issue by SeekPoint** [candlewill/Chinsese_word_vectors#1]

**Comment by candlewill** [comment]
zht2zhs.ini is just a parameter for opencc tool, not a file name.

**Comment by SeekPoint** [comment]
rzai@rzai00:~/prj/Chinsese_word_vectors$ opencc -i ../../rz_prj/zhwiki/wiki.zh.text -o ../../rz_prj/zhwiki/wiki.zh.text.traditional -c zhs2zht.ini 
zhs2zht.ini not found or not accessible.
rzai@rzai00:~/prj/Chinsese_word_vectors$

**Comment by SeekPoint** [comment]
I find the  zhs2zht.ini  in opencc-python
however, 

rzai@rzai00:~/prj/Chinsese_word_vectors$ opencc -i ../../rz_prj/zhwiki/wiki.zh.text -o ../../rz_prj/zhwiki/wiki.zh.text.traditional -c ../opencc-python/opencc/data/zhs2zht.ini 
Invalid format: Error parsing JSON
rzai@rzai00:~/prj/Chinsese_word_vectors$

**Comment by SeekPoint** [comment]
this error occurs when I do the installation from source  code ,
it can fix just by apt-get install opencc

my os is ubuntu14
